language: node_js
node_js:
  - "12"

branches:
  except:
  - master

script:
  - npm run build -- --prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist/evan-suau/
  target-branch: master
  on:
    branch: release
