language: node_js
node_js:
  - "10"

branches:
  except:
  - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist/
  target-branch: master
  on:
    branch: gh-pages
