name: Test and build

on: 
  push:
    branches-ignore:
    - master
    - release

jobs:
  test:
    name: Test app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm install
    - name: Run unit tests
      run: npm run test 
  build:
    name: Build app
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm install
    - name: Run Angular build
      run: npm run build -- --prod
      